### ISSUE TITLE
Bugs with showing the DFT button in some setups

### ISSUE THREAD

**Issue by AlexYeCu** [7adietri/document-font-toggle#6]
Button not shown with classic theme restorer if address bar removed from (navigation) panel.
How to reproduce:
1. Install add-on, watch the DFT button.
2. Restart firefox.
3. No button!
4. Switch off Classic Theme Restorer to retune buttons (thanx to those, who`ve made  Australis — worst FF innovation ever!), restart firefox.
5. Here is the DFT button, but address bar too!
6. Removing bar from panel — button lost again.
Why to remove the bar: this is standart setup for Vimperator.

**Comment by 7adietri** [comment]
DFT 2.0 uses a button type that was introduced with Australis. That's probably why it breaks if you somehow remove the Australis UI, sorry.
