### ISSUE TITLE
Add-on button disappeared in recent Firefox versions(?)

### ISSUE THREAD

**Issue by green-tea** [7adietri/document-font-toggle#7]
The add-on bar button seems to have disappeared in recent Firefox versions, and I can't find it in the customize dialog. (I'm also using the Addon Bar Restored! addon.) I'm using Firefox 36.0 right now, but this seems to have been a problem for at least a few weeks.

I imagine that this has something to do with all the recent changes to the Firefox UI. Having said that, I'm also running pentadactyl with most toolbars hidden, so there's a possibility it's a problem at my end too.

**Comment by 7adietri** [comment]
Hi, recent versions of DFT are using Australis functionality for the button. My guess would also be that removing or hiding the Australis UI might be the issue.
