### ISSUE TITLE
Exclude installed extensions

### ISSUE THREAD

**Issue by GreenLunar** [7adietri/document-font-toggle#9]
Do not prevent from installed extensions to use own fonts.

Some users may use extensions that use own fonts, such as [uMatrix](https://github.com/gorhill/uMatrix).

**Comment by 7adietri** [comment]
DFT is just a very crude switch for the global "Allow pages to choose their own fonts" setting, so it's all or nothing I'm afraid.

**Comment by GreenLunar** [comment]
Not necessarily.  Please follow the following steps.

1. Set *Startup State* to Disable.
2. Go to a website that is listed in *Always Allow*.
3. Enable custom fonts to this website.
4. Switch to tab of website that is listed in *Always Allow*.
5. Go back to tab of a website is listed in *Always Allow*.
6. Disable custom fonts to this website.

* uMatrix should still have its fonts displayed.
